export const cores = [
  {
    id: "barrage",
    name: "弹幕",
    evolution: "风暴",
    tag: "射击",
    color: "#f9d879",
    desc: "2 弹药发射 3 枚散射弹；找平台补弹。",
    goal: "收集两种射击遗物 → 风暴五连发",
  },
  {
    id: "leap",
    name: "跃击",
    evolution: "雷链",
    tag: "踩踏",
    color: "#91d8be",
    desc: "踩怪产生冲击并高弹跳；寻找连续落脚点。",
    goal: "收集两种踩踏遗物 → 雷链大范围冲击",
  },
  {
    id: "fall",
    name: "陨落",
    evolution: "地裂",
    tag: "重坠",
    color: "#ef907e",
    desc: "高速落地释放冲击波；射击制动较弱。",
    goal: "收集两种重坠遗物 → 地裂沿平台扩散",
  },
] as const;
export type CoreId = (typeof cores)[number]["id"];
export const upgrades = [
  {
    id: "pierce",
    name: "穿井针",
    tag: "射击",
    desc: "子弹穿透 1 / 2 个非装甲敌人。",
    family: "barrage",
    color: "#f9d879",
  },
  {
    id: "power",
    name: "聚能匣",
    tag: "射击",
    desc: "补弹后的第一发伤害 +1 / +2。",
    family: "barrage",
    color: "#f9d879",
  },
  {
    id: "split",
    name: "余震弹",
    tag: "射击",
    desc: "射击击杀释放伤害 1 的脉冲，半径 45 / 65。",
    family: "barrage",
    color: "#f9d879",
  },
  {
    id: "shock",
    name: "连锁雷",
    tag: "踩踏",
    desc: "踩怪向另一敌人传导 1 点伤害，范围 90 / 130。",
    family: "leap",
    color: "#91d8be",
  },
  {
    id: "bounce",
    name: "弹簧跟",
    tag: "踩踏",
    desc: "踩怪弹起速度额外增加 40 / 70。",
    family: "leap",
    color: "#91d8be",
  },
  {
    id: "hover",
    name: "猎手眼",
    tag: "踩踏",
    desc: "标记附近可踩目标，范围 140 / 200。",
    family: "leap",
    color: "#91d8be",
  },
  {
    id: "slam",
    name: "冲击环",
    tag: "重坠",
    desc: "强化高速落地波；普通枪靴也获得小冲击波。",
    family: "fall",
    color: "#ef907e",
  },
  {
    id: "rapid",
    name: "接地甲",
    tag: "重坠",
    desc: "高速落地抵伤 0.25 / 0.4 秒，冷却 2 秒。",
    family: "fall",
    color: "#ef907e",
  },
  {
    id: "combo",
    name: "破岩靴",
    tag: "重坠",
    desc: "高速落地破岩并穿过；二级伤害岩下敌人。",
    family: "fall",
    color: "#ef907e",
  },
  {
    id: "ammo",
    name: "扩容匣",
    tag: "通用",
    desc: "弹药上限 +2 / +4；不会凭空补弹。",
    family: "general",
    color: "#aebbe9",
  },
  {
    id: "shield",
    name: "旧日护符",
    tag: "通用",
    desc: "每关抵挡首次伤害；二级延长抵伤后无敌。",
    family: "general",
    color: "#aebbe9",
  },
  {
    id: "heal",
    name: "采晶器",
    tag: "通用",
    desc: "每次击杀额外获得 1 / 2 晶石。",
    family: "general",
    color: "#aebbe9",
  },
] as const;
export type UpgradeId = (typeof upgrades)[number]["id"];
export const W = 420,
  FLOOR = 5200;

export const characters = [
  {
    id: "scout",
    name: "探井者",
    tag: "均衡",
    desc: "标准枪靴，适合熟悉路线。",
    hp: 4,
    ammo: 8,
    speed: 240,
    fireRate: 1,
    tint: 0xffffff,
    color: "#91d8be",
  },
  {
    id: "warden",
    name: "铁卫",
    tag: "生存",
    desc: "生命更多，移动较慢，弹匣较小。",
    hp: 6,
    ammo: 6,
    speed: 205,
    fireRate: 1,
    tint: 0xf9d879,
    color: "#f9d879",
  },
  {
    id: "ranger",
    name: "游隼",
    tag: "敏捷",
    desc: "移动更快、开火更快，生命较少。",
    hp: 3,
    ammo: 8,
    speed: 285,
    fireRate: 0.85,
    tint: 0x9dc9ff,
    color: "#9dc9ff",
  },
  {
    id: "gunner",
    name: "火花",
    tag: "火力",
    desc: "大弹匣，生命较少，移动略慢。",
    hp: 3,
    ammo: 12,
    speed: 225,
    fireRate: 1,
    tint: 0xef907e,
    color: "#ef907e",
  },
] as const;
export type CharacterId = (typeof characters)[number]["id"];

export function relicEffect(id: UpgradeId, level: number) {
  const two = level >= 2;
  const effects: Record<UpgradeId, string> = {
    pierce: `子弹穿透 ${two ? 2 : 1} 个非装甲敌人。`,
    power: `每次补弹后，第一发伤害 +${two ? 2 : 1}。`,
    split: `射击击杀产生伤害 1 的脉冲，范围 ${two ? 65 : 45}；不会连锁触发。`,
    shock: `踩怪向另一敌人传导 1 点伤害，范围 ${two ? 130 : 90}。`,
    bounce: `踩怪弹起速度额外增加 ${two ? 70 : 40}。`,
    hover: `标记距离 ${two ? 200 : 140} 内的可踩目标。`,
    slam: `高速落地冲击半径 +${two ? 40 : 20}；普通枪靴获得半径 ${two ? 90 : 70}、伤害 1 的落地波。`,
    rapid: `高速落地抵伤 ${two ? "0.4" : "0.25"} 秒，冷却 2 秒。`,
    combo: `高速落地破坏接触岩块，保留下落速度。${two ? "对岩下范围 50 造成 1 点伤害。" : ""}`,
    ammo: `弹药上限 +${two ? 4 : 2}；容量提升不会补弹。`,
    shield: `每关抵挡首次伤害。${two ? "抵挡后无敌延长 0.5 秒。" : ""}`,
    heal: `每次击杀额外获得 ${two ? 2 : 1} 晶石。`,
  };
  return effects[id];
}
